// -*- coding: utf-8 -*-
// vim: set fileencoding=utf-8

#ifndef ANTIQUA_GLOBAL_H
#define ANTIQUA_GLOBAL_H

#ifndef ANTIQUACRM_NAME
#define ANTIQUACRM_NAME "@PROJECTNAME@"
#endif

#ifndef ANTIQUACRM_DISPLAYNAME
#define ANTIQUACRM_DISPLAYNAME "@DISPLAYNAME@"
#endif

#ifndef ANTIQUACRM_VERSION
#define ANTIQUACRM_VERSION "@ANTIQUACRM_VERSION_MAJOR@.@ANTIQUACRM_VERSION_MINOR@.@ANTIQUACRM_VERSION_RELEASE@"
#endif

#ifndef ANTIQUACRM_VERSION_STRING
#define ANTIQUACRM_VERSION_STRING "@ANTIQUACRM_VERSION_STRING@"
#endif

#ifndef HJCMS_CONFIG_DOMAIN
#define HJCMS_CONFIG_DOMAIN "de.hjcms"
#endif

#include <QtCore/QtGlobal>
#if defined(ANTIQUACORE_LIBRARAY)
# define ANTIQUACORE_EXPORT Q_DECL_EXPORT
#else
# define ANTIQUACORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ANTIQUA_GLOBAL_H
