#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8

set +x

_ts_files=$(find ./i18n -maxdepth 1 -type f -name "*_de.ts")
_linguist="`ls ~/Programme/Qt/6*/gcc_64/bin/linguist`"

${_linguist} ./i18n/antiquacore_de.ts
