#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8

set +x

if test -d ~/Developement/antiqua ; then
  rm -rf ~/Developement/antiqua/build-antiquacrm-*
  find ~/Developement/antiqua -type f -name "*~" -exec rm -v "{}" \;
fi

function __check_sub_project()
{
  local _f=${1:-"."}/CMakeLists.txt
  if test -s ${_f} ; then
    grep -e '_subproject\b\s\+\"' ${_f} | cut -d'"' -f2
  fi
}

function __create_header_subs()
{
  _scope=${1:-"failed"}
  _namespace=""
  if test -n "$2" ; then
    _namespace="$(echo $2 | awk '{print toupper($1)}')_"
  fi
  _dest=$(echo ${_scope} | awk '{print tolower($1)}')
  _module=$(echo ${_scope} | awk '{print toupper($1)}')
  if test -d ${_dest} ; then
  pushd ${_dest}
  cat > ${_scope} <<EOF
// -*- coding: utf-8 -*-
// vim: set fileencoding=utf-8
EOF
    for _h in $(ls *.h | sort) ; do
      _class=$(echo ${_h} | sed 's,\.h,,' | awk '{print toupper($1)}')
  cat >> ${_scope} <<EOF
#ifndef ${_namespace}${_class}_${_module}_H
#include "${_h}"
#endif
EOF
    done
  cat >> ${_scope} <<EOF
// EOF
EOF
  popd
  fi
}

echo "# Build Sub Header Processing"
__create_header_subs Utils
__create_header_subs Imaging
__create_header_subs SqlCore HJCMS

echo "# CMAKE Targets" > CMakeSubTargets.cmake

cat > CMakeSubTargets.cmake <<EOF
##
# Generated by $0
##
SET (TARGET_INCLUDE_DIRS
 \${PROJECT_INCLUDE_DIRS}
 \${CMAKE_CURRENT_BINARY_DIR}/src
 \${CMAKE_CURRENT_SOURCE_DIR}/src
EOF

declare -a _buffer=();

for _t in $(find . -mindepth 1 -maxdepth 1 -type d -exec basename "{}" \;) ; do
if test -e ${_t}/CMakeLists.txt ; then
  _buffer+=(${_t})
  cat >> CMakeSubTargets.cmake <<EOF
 \${CMAKE_CURRENT_BINARY_DIR}/${_t}
 \${CMAKE_CURRENT_SOURCE_DIR}/${_t}
EOF
fi
done

cat >> CMakeSubTargets.cmake <<EOF
 \${CMAKE_CURRENT_BINARY_DIR}/src
 \${CMAKE_CURRENT_SOURCE_DIR}/src
)

INCLUDE_DIRECTORIES (\${TARGET_INCLUDE_DIRS})

EOF

for _s in ${_buffer[@]} ; do
cat >> CMakeSubTargets.cmake <<EOF
ADD_SUBDIRECTORY (${_s})
EOF
done

cat >> CMakeSubTargets.cmake <<EOF

SET(_link_sub_libs
EOF

for _s in ${_buffer[@]} ; do
  __check_sub_project ${_s} >> CMakeSubTargets.cmake
done

cat >> CMakeSubTargets.cmake <<EOF
)

EOF

