SET (PROJECT_INCLUDE_DIRS
	${CMAKE_CURRENT_BINARY_DIR}/widgets
	${CMAKE_CURRENT_SOURCE_DIR}/widgets
	${CMAKE_CURRENT_BINARY_DIR}/tabs/books
	${CMAKE_CURRENT_SOURCE_DIR}/tabs/books
	${CMAKE_CURRENT_BINARY_DIR}/libs/core
	${CMAKE_CURRENT_SOURCE_DIR}/libs/core
	${PROJECT_INCLUDE_DIRS}
)

INCLUDE_DIRECTORIES (${PROJECT_INCLUDE_DIRS})

SET(PROJECT_LIBRARIES
	AntiquaBooks
	AntiquaWidgets
	AntiquaCRM
)

