SET (PROJECT_INCLUDE_DIRS
	${CMAKE_CURRENT_BINARY_DIR}/tabs/books
	${CMAKE_CURRENT_SOURCE_DIR}/tabs/books
	${CMAKE_CURRENT_BINARY_DIR}/widgets
	${CMAKE_CURRENT_SOURCE_DIR}/widgets
	${CMAKE_CURRENT_BINARY_DIR}/lib
	${CMAKE_CURRENT_SOURCE_DIR}/lib
	${CMAKE_CURRENT_BINARY_DIR}/utils/preloader
	${CMAKE_CURRENT_SOURCE_DIR}/utils/preloader
	${PROJECT_INCLUDE_DIRS}
)

INCLUDE_DIRECTORIES (${PROJECT_INCLUDE_DIRS})

SET(PROJECT_LIBRARIES
	AntiquaBooks
	AntiquaWidgets
	AntiquaCRM
	AntiquaPreloader
)

